---
apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: true
    useDockerCLI: true
  tagPolicy:
    customTemplate:
        template: "{{.PREFIX}}"
        components:
        - name: PREFIX
          gitCommit: 
            prefix: "skaffold-"
        # - name: DATE
        #   dateTime:
        #     format: "2006-01-02_15-04-05.999_MST"
        #     timezone: "Local"
  artifacts:
    - image: devmyungyun/automation-server
      context: .
      sync:
        manual:
          - src: './**/*'
            dest: .        
deploy:
  kubectl:
    manifests:
      - ./k8s/*